#include "C_Ping_Packet.h"
#include "C_SYN_Packet.h"

#include "G_Auto_Notify_Packet.h"
#include "G_Auto_Request_Packet.h"
#include "G_Move_Notify_Packet.h"
#include "G_Move_Request_Packet.h"
#include "G_Ping_Packet.h"
#include "G_Primary_Defs.h"
#include "G_Primary_Notify_Packet.h"
#include "G_Primary_Request_Packet.h"

#include "I_Auto_Packet.h"
#include "I_LastHit_Packet.h"
#include "I_Local_Player_Packet.h"
#include "I_Minion_Packet.h"
#include "I_Objective_Packet.h"
#include "I_Primary_Packet.h"
